### ISSUE TITLE
[Minor] conflation of data and GUI parameters logic

### ISSUE THREAD

**Issue by vigji** [calebweinreb/SNUB#11]
I have been reading the functions for the project creation, and I am bit confused by the conflation of the (thin) data-munging logic and the visualization settings logic in the same functions.

Maybe it would be better to separate the part where one links to the project all the available data and the part where one specifies the default parameters for the GUI.

**Comment by niksirbi** [comment]
There is a related issue to that one.

As a user, I would like to be able to change visualisation parameters like `vmin`, `vmax`, `colormap`, `linewidth` etc. directly in the GUI. It's a bit weird to pre-specify these when adding data to the project, because at that point you haven't seen the data and you might not know what visualisation parameters are appropriate. Some of these parameters are editable from the GUI, but not all of them.

**Comment by calebweinreb** [comment]
The overall rationale for ingesting data and setting plotting parameters in a single function is explained here https://github.com/calebweinreb/SNUB/issues/11

It is a good point that though that users might wish to make further adjustments once the SNUB plot is already open, especially ones that could potentially impact the legibility of the plot. I just merged https://github.com/calebweinreb/SNUB/pull/28 that makes a few more parameters adjustable in the GUI:
- scatter plot: users can now adjust marker size and border width directly in the GUI
- trace plot: users can adjust linewidth and y-axis bounds in the GUI

These parameter changes are not saved to the config (currently the GUI never directly changes the config and I'd like to keep it that way).
