### ISSUE TITLE
[Major] package deployment via pip

### ISSUE THREAD

**Issue by vigji** [calebweinreb/SNUB#13]
Since there are no difficult dependencies in the project (and no environment file necessary as a result), I would highly recommend distribute the package via PyPI/`pip`, so that it can be more easily installed and kept updated by all users.

**Comment by niksirbi** [comment]
Agreed, deployment on pip would be feasible and could enable a one-line install (`pip install snub`) on most platforms. It's worth pursuing sooner rather than later since it will make SNUB much more accessible.

Once the first release is deployed, update releases can be automated via GitHub Actions. Some example action workflows can be found [here](https://github.com/neuroinformatics-unit/actions).

**Comment by calebweinreb** [comment]
SNUB is now available via pip https://pypi.org/project/systems-neuro-browser/

The name ``snub`` was already taken on PyPI, so to install, users will have to run ``pip install systems-neuro-browser`` although they will still ``import snub`` in python and run ``snub`` from the command line. 

I chose not to implement automatic updates (e.g. via GitHub Actions) since I will remain the main developer for the foreseeable future and can perform the updates manually.

**Comment by niksirbi** [comment]
I can confirm that `pip install systems-neuro-browser` works! Thanks.
