### ISSUE TITLE
[Minor] Some small UI bugs and suggestions

### ISSUE THREAD

**Issue by niksirbi** [calebweinreb/SNUB#23]
When using the SNUB GUI on my M2 Macbook I encountered several small "glitches". I chose to group them all here instead of opening a separate issue for each. Some of these are "bugs", and other others are suggestions for UI/UX improvement. None of these are critical, but cumulatively they may lead to user frustration.

## Bugs

- Pressing the `Esc` button removes the UMAP scatterplot, without an obvious way to bring it back.
- In the calcium imaging sample project, selecting the row labels on the heatmap generates the corresponding trace, while this doesn't work for spike plots in the ephys project. "Right click -> Plot trace" works for both of them. As a user, I would expect identical behaviour from these two types of plots - i.e. clicking a row label should plot the trace in both cases.
- The play button and the "Track playhead" checkbox do not display properly for me.

![Screenshot 2024-01-30 at 18 10 06](https://github.com/calebweinreb/SNUB/assets/20923448/53ae1b1e-344d-43eb-a1c6-7ab771fda180)

## Suggestions

- Add a "Help" button or similar to show the most important shortcuts and functionalities. There are many useful tricks for using the interface (documented [here](https://snub.readthedocs.io/en/latest/tutorials.html#using-the-interface)), but they are easily forgotten till you get very familiar with them. A list of shortcuts. easily accessible from the GUI would facilitate the learning process.
- It is hard to select a specific cell in heatmaps and trace plots when there are many cells. In heatmaps the row labels are very closely bunched together, while in trace plots the dropdown gives you an enormous vertical list of cells. I don't know what the solution is, just marking it as a point that would benefit from improvement.

**Comment by calebweinreb** [comment]
Thanks for the detailed list! I believe I'd addressed all the points above (except perhaps suggestion bullet 2).

- Pressing `Esc` no longer hides the scatter plot (https://github.com/calebweinreb/SNUB/pull/26)
- Spike plots now behave like heatmaps: clicking on row labels causes the corresponding trace to appear (https://github.com/calebweinreb/SNUB/pull/27/commits/b3c5fc25a3691fdd6d5016bf28eea5170ecc7e20)
- This absence of a play button and other icons was related to the corresponding icon images not being included in the package data. This is now fixed (https://github.com/calebweinreb/SNUB/pull/27/commits/93062068a97af4502ededab25ea8d050aa3dae80). 
- I added a help menu that includes comprehensive explanations of all the tips/tricks for navigating the GUI (see  https://github.com/calebweinreb/SNUB/pull/29 and screenshots). 
- The bunching of labels in the heatmap is a good point. I think vertical zoom and other features make it pretty easy to go from a row of the heatmap to a row label, but it's quite hard to go in the other direction, finding a row from its label. However, I think this wouldn't be such a common use case e.g. when viewing large-population neural recordings.
- I think the giant drop-down menu for the trace plot is more manageable since the labels are sorted alphabetically. 
<img width="365" alt="Screenshot 2024-02-22 at 4 20 12 PM" src="https://github.com/calebweinreb/SNUB/assets/6147762/4593c99a-4005-40dd-89b7-aa07146661b2">
<img width="400" alt="Screenshot 2024-02-22 at 4 20 41 PM" src="https://github.com/calebweinreb/SNUB/assets/6147762/cc3ea884-ebed-49c1-aa82-afbb89f29eca">

**Comment by niksirbi** [comment]
Thanks for implementing all the suggestions! The help menu especially looks great!

I tried to double-check that these work on my machine by pip installing from the current `main` branch (in a fresh conda environment with Python 3.8). But the dependencies failed to resolve. Could you double check that some of the newly introduced dependencies do not cause version incompatibilities?

**Comment by calebweinreb** [comment]
Thanks for checking! I tried installing from pip (which contained the equivalent of the main branch) with no issues on Mac and Linux (incidentally there was a circular import error when I tried to run SNUB, but that us now fixed). 

What OS were you using? And what error was produced?

**Comment by niksirbi** [comment]
Oh I see, I had tried to install from git by `pip install -e .` in the local repository's root, because I thought the PyPI version (0.0.3) is way behind the GitHub release.
I tried it again now, this time installing from pip and it worked! I can also verify that your UI fixes have worked, so we can close this issue.

I'm on Apple M2, Sonoma 14.3.1 btw. But I thinks this is not so relevant anymore. The documented way of installation clearly works.
