### ISSUE TITLE
[JOSS] Implement automated testing via CI

### ISSUE THREAD

**Issue by lucasmiranda42** [calebweinreb/SNUB#30]
I think SNUB is a great tool, and has the potential to be used by quite some people!

That said, and especially given this is the case, I would strongly recommend implementing automated testing via CI (using something like [travis-ci](https://www.travis-ci.com/), for example). I think this will make keeping track of potential issues much easier as the package grows.

This issue is part of a paper review for [JOSS](https://github.com/openjournals/joss-reviews/issues/6187).

**Comment by calebweinreb** [comment]
Thanks for the suggestion! I created a github action that runs pytest and checks black formatting on pushes/PRs to `main`. I also created protections for `main` so that all merges require a PR. 

Here's the github action config: https://github.com/calebweinreb/SNUB/blob/main/.github/workflows/ci.yml
Here's a log of the last completed action: https://github.com/calebweinreb/SNUB/actions/runs/8125132061/job/22207389372
