### ISSUE TITLE
[Major] No support for standard neurodata formats

### ISSUE THREAD

**Issue by vigji** [calebweinreb/SNUB#9]
As the package aims at helping out people dealing with their own recordings and experiments, it would greatly benefit from supporting standard neuro data formats.

I believe that the impact of the tool would be way larger if there were some more integration with the existing ecosystem of data formats, in the current shape it feels a bit a lab-specific tool (format-wise), instead of forcing the user to structure their dataset to the highly specific requirements of the package. I could recommend for example look for at least proof-of-principle integration with NWB, or SpikeInterface.

A good way of smoothing this up would be to showcase the software on openly accessible datasets, instead of the custom datasets provided as examples.

**Comment by calebweinreb** [comment]
Thanks for the suggestion! 

Right now the software is relatively format-agnostic. Most of the io functions ingest numpy arrays directly, rather than paths to data in a specific format. So in a sense it is no more format-specific than matplotlib. 

I agree that interfacing with standard formats would be useful through. To that end, we developed a conversion tool that generates SNUB datasets directly from NWB files (see https://github.com/calebweinreb/SNUB/pull/17). See documentation here: https://github.com/calebweinreb/SNUB/blob/dev/docs/source/nwb.rst

**Comment by vigji** [comment]
I see the point that you make in referring to it as an almost matplotlib-like tool in being data-agnostic. Still, I feel that including pipelines to generate the data from nwb files does lower the energy barrier for adoption for new users, and gives a good tool to dig into open datasets. I feel that this is addressed now!
